export const INCREASE_VALUE = "INCREASE_VALUE";
export const DECREASE_VALUE = "DECREASE_VALUE";

export const TEST_INCREASE_VALUE = "TEST_INCREASE_VALUE";
export const TEST_DECREASE_VALUE = "TEST_DECREASE_VALUE";

export const RESET_STATE = "RESET_STATE";
